name: Build and upload with compose

on:
  push:
    branches:
      - master
    paths:
      - compose.yaml

  pull_request:
    branches:
      - master
    paths:
      - compose.yaml

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@4
    - name: Build the Docker image
      run: |
          docker compose build
          docker login ghcr.io -u Luo-Hong-Jun -p ${{ secrets.GHCR_TOKEN }}
          docker compose push